server.port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://j9c208.p.ssafy.io:8761/eureka
#      defalutZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mariadb://j9c208.p.ssafy.io:3309/payment
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: bigbigred
    hikari:
      idle-timeout: '600000'
      maximum-pool-size: '50'
      auto-commit: 'true'
      connection-init-sql: SELECT 1
      driver-class-name: org.mariadb.jdbc.Driver
      connection-timeout: '5000'
      pool-name: HikariPool
      max-lifetime: '1800000'
      minimum-idle: '50'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true
  redis:
    port: 6379
    host: j9c208.p.ssafy.io
  devtools:
    livereload:
      enabled: 'true'
  profiles:
    include: env

logging:
  level:
    root: info
    org:
      springframework:
        boot : info
        security : DEBUG
        web : info
  file:
    name: ./payment-service.log
build:
  date: '@build.date@'
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'
custom:
#  url: "http://localhost:8000"
  url: "https://j9c208.p.ssafy.io"
  key:
    kakao:
      admin: "KakaoAK 0bb552e7d47960ca57ceeb4950548b8b"
---


